// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY739ao2W6x3kw_eODHTI7-lgXgjXecZ0',
    appId: '1:778373320188:web:217805196717066488f679',
    messagingSenderId: '778373320188',
    projectId: 'jr-linguist-85a69',
    authDomain: 'jr-linguist-85a69.firebaseapp.com',
    storageBucket: 'jr-linguist-85a69.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqSEa7SJuSOX5PDFzW6QdbVzvLuadL7ro',
    appId: '1:778373320188:android:3de6252b614da37488f679',
    messagingSenderId: '778373320188',
    projectId: 'jr-linguist-85a69',
    storageBucket: 'jr-linguist-85a69.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD647r1D0HimV33yzSOiBd-loKijM3hTFo',
    appId: '1:778373320188:ios:734e77c38f25346f88f679',
    messagingSenderId: '778373320188',
    projectId: 'jr-linguist-85a69',
    storageBucket: 'jr-linguist-85a69.appspot.com',
    iosClientId: '778373320188-mf5j1lu2q8rc5haf9hj58l5n4n9imdn3.apps.googleusercontent.com',
    iosBundleId: 'com.example.jrLinguist',
  );
}
